spring:
  application:
    name: asset-management-application


database:
  default-hikari-properties:
    minimum-idle: 1
    maximum-pool-size: 2
    connection-timeout: 5000
    idle-timeout: 15000
    max-lifetime: 60000
    leak-detection-threshold: 2000
  postgres:
    asset:
      schema: asset
      package-names:
        datasource: assetDatasource
        namedParameterJdbcTemplate: assetNamedParameterJdbcTemplate
        containerEntityManagerFactory: assetContainerEntityManagerFactory
        platformTransactionManager: assetPlatformTransactionManager
        entity: com.karur.realty_management_application.entity
        repository: com.karur.realty_management_application.repository
      jdbc-url: jdbc:postgresql://localhost:4000/asset
      username: postgres
      password: postgres
      driver-class-name: org.postgresql.Driver
      hikari:
        schema: asset
        connection-test-query: SELECT 1
      jpa:
        show-sql : true
        properties:
          hibernate:
            ddl-auto: update
            dialect: org.hibernate.dialect.PostgreSQLDialect
            format_sql: true